backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: '/assets'

collections:
  - name: 'home'
    label: 'Home page'
    folder: 'src/pages/home'
    create: true
    fields:
      - { name: 'published', label: 'Published', widget: 'hidden', default: true }
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'socials'
    label: 'Socials'
    folder: 'src/pages/socials'
    create: true
    fields:
      - { name: 'published', label: 'Published', widget: 'hidden', default: true }
      - { name: 'title', label: 'Title', widget: 'string' }
      - {
          name: 'position',
          label: 'Position on the footer',
          widget: 'number',
          required: true,
          valueType: int,
          min: 1,
          max: 99,
      }
      - name: 'icon'
        label: 'Icon'
        widget: 'select'
        options: ['Facebook', 'Twitter', 'Instagram', 'GooglePlus', 'YouTube']
      - { name: 'link', label: 'Link', widget: 'string' }

  - name: 'medals'
    label: 'Medals'
    folder: 'src/pages/medals'
    create: false
    fields:
      - { name: 'published', label: 'Published', widget: 'hidden', default: true }
      - { name: 'title', label: 'Title', widget: 'string' }
      - {
          name: 'gold',
          label: 'Gold medals',
          widget: 'number',
          required: true,
          valueType: int,
          min: 1,
      }
      - {
          name: 'silver',
          label: 'Silver medals',
          widget: 'number',
          required: true,
          valueType: int,
          min: 1,
      }
      - {
          name: 'bronze',
          label: 'Bronze medals',
          widget: 'number',
          required: true,
          valueType: int,
          min: 1,
      }

  - name: 'timetable'
    label: 'Timetable'
    folder: 'src/pages/timetable'
    create: true
    fields:
      - { name: 'published', label: 'Published', widget: 'hidden', default: true }
      - { name: 'title', label: 'Branch Name', widget: 'string' }
      - { name: 'monday', label: 'Monday', widget: 'text', required: false }
      - { name: 'tuesday', label: 'Tuesday', widget: 'text', required: false }
      - { name: 'wednesday', label: 'Wednesday', widget: 'text', required: false }
      - { name: 'thursday', label: 'Thursday', widget: 'text', required: false }
      - { name: 'friday', label: 'Friday', widget: 'text', required: false }
      - { name: 'saturday', label: 'Saturday', widget: 'text', required: false }
      - { name: 'sunday', label: 'Sunday', widget: 'text', required: false }

  - name: 'news'
    label: 'News'
    folder: 'src/pages/news'
    create: true
    fields:
      - { name: 'published', label: 'Published', widget: 'boolean', default: true }
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'date', label: 'Date', widget: 'datetime' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'team'
    label: 'Team'
    folder: 'src/pages/team'
    create: true
    fields:
      - { name: 'published', label: 'Published', widget: 'boolean', default: true }
      - {
          name: 'position',
          label: 'Position on the team page',
          widget: 'number',
          required: true,
          valueType: int,
          min: 1,
          max: 99,
        }
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'avatar', label: 'avatar', widget: 'image' }
      - { name: 'body', label: 'Description', widget: 'markdown' }

  - name: 'disciplines'
    label: 'Disciplines'
    folder: 'src/pages/disciplines'
    create: true
    fields:
      - { name: 'published', label: 'Published', widget: 'boolean', default: true }
      - {
          name: 'position',
          label: 'Position on the homepage page',
          widget: 'number',
          required: true,
          valueType: int,
          min: 1,
          max: 9,
        }
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'body', label: 'Description', widget: 'markdown' }
  - name: 'legal'
    label: 'Legal'
    folder: 'src/pages/legal'
    create: true
    fields:
      - { name: 'published', label: 'Published', widget: 'boolean', default: true }
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
