service: rhythmic-excellence-mail-sender

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 512
  timeout: 10
  stage: production
  versionFunctions: false
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
      Resource: '*'
  usagePlan: # Optional usage plan configuration
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  send:
    handler: handler.send
    name: ${self:provider.stage}-rhythmicExcellenceMailsender
    description: Send emails coming from rhythmicexcellence website
    memorySize: 512
    timeout: 10
    events:
      - http:
          path: send
          method: post
          cors:
            origins:
              - 'https://www.rhythmicexcellence.london'
            headers:
              - Content-Type
              - MY_CUSTOM_HEADER
              - X-Api-Key

package:
  exclude:
    - node_modules/**
  include:
    - node_modules/serverless-offline/**

plugins:
  - serverless-offline
