service: rhythmic-excellence-mail-sender

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  memorySize: 512
  timeout: 8
  stage: production
  versionFunctions: false
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
      Resource: '*'
  usagePlan: # Optional usage plan configuration
    quota:
      limit: 1000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 100
      rateLimit: 50

functions:
  send:
    handler: handler.send
    name: ${self:provider.stage}-rhythmicExcellenceMailsender
    description: Send emails coming from RhythmicExcellence website
    memorySize: 512
    timeout: 8
    events:
      - http:
          path: send
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Api-Key

package:
  exclude:
    - node_modules/**
  include:
    - node_modules/serverless-offline/**

plugins:
  - serverless-offline
